# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wolf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
